### ISSUE TITLE
有一些用户行为导致的exception，不想让钉钉提示，写到dontReport里，但是好像没生效；

### ISSUE THREAD

**Issue by xbpk3t** [wujunze/dingtalk-exception#2]
求助；

**Comment by xbpk3t** [comment]
if (isPro() === true && $this->shouldReport($exception)) {
			DingTalkExceptionHelper::notify($exception, true);
		}


需要手动加一个shouldReport()方法；

**Comment by wujunze** [comment]
@JeffcottLu   这个问题解决了吗
